bot:
    token: 1853812802:AAGml0nJh-Dd3R19sJO-sXbUPBsXD-swAZg
    parse_mode: html

executor:
    skip_updates: true

modules:
    - handlers.main
    - handlers.errors

log_ignore:
    - aiogram
    - asyncio
    - aiogram.Middleware

commands:
    start: Начать беседу со мной
