bot:
    token: 1872281657:AAFJc8rX1tF1noGDJZL7DSP8C9bzPUbTF2U
    parse_mode: html

executor:
    skip_updates: true

modules:
    - handlers.main
    - handlers.errors

log_ignore:
    - aiogram
    - asyncio
    - aiogram.Middleware

commands:
    start: Начать беседу со мной
