bot:
    token: 1615030280:AAFgBwNLC1KpFdEp0liWlOrtykC2e1Pmg6s
    parse_mode: html

executor:
    skip_updates: true

modules:
    - handlers.main
    - handlers.errors

log_ignore:
    - aiogram
    - asyncio
    - aiogram.Middleware

commands:
    start: Начать беседу со мной
