bot:
    token: 1865508975:AAGiigtv5YcHE11AiJ0AvEvdUG9XV_2jNkE
    parse_mode: html

executor:
    skip_updates: true

modules:
    - handlers.main
    - handlers.errors

log_ignore:
    - aiogram
    - asyncio
    - aiogram.Middleware

commands:
    start: Начать беседу со мной
