bot:
    token: 1974055157:AAGMZbEPkK7KRrAgl1y1OlHbVy-46_BosWk
    parse_mode: html

executor:
    skip_updates: true

modules:
    - handlers.main
    - handlers.errors

log_ignore:
    - aiogram
    - asyncio
    - aiogram.Middleware

commands:
    start: Начать беседу со мной
